# Site settings
title: Quagmire
email: rao.thejaswi@gmail.com
description: >-
  Stuff I find cool/useful
baseurl: "/blog"
url: "https://teju85.github.io"
github_username: teju85
maxhomeposts: 1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
kramdown:
  math_engine: katex

# Exclude from processing. The following items will not be processed, by default.
exclude:
  - Gemfile
  - Gemfile.lock
